package dev.questweaver.domain.usecases

import dev.questweaver.domain.events.GameEvent
import kotlinx.serialization.Serializable

/**
 * Sealed class representing the result of a use case operation.
 * Enables exhaustive when expressions for handling different outcome scenarios.
 */
sealed class ActionResult {
    /**
     * Successful operation that produced one or more game events.
     *
     * @property events The list of GameEvent instances generated by the operation
     */
    data class Success(val events: List<GameEvent>) : ActionResult()

    /**
     * Failed operation with a descriptive reason.
     *
     * @property reason Human-readable explanation of why the operation failed
     */
    data class Failure(val reason: String) : ActionResult()

    /**
     * Operation requires user choice before proceeding.
     *
     * @property options The list of available choices for the user to select from
     */
    data class RequiresChoice(val options: List<ActionOption>) : ActionResult()
}

/**
 * Represents a choice option that the user can select.
 *
 * @property id Unique identifier for this option
 * @property description Human-readable description of what this option does
 * @property metadata Additional context data for this option (e.g., spell slot level, target creature)
 */
@Serializable
data class ActionOption(
    val id: String,
    val description: String,
    val metadata: Map<String, String> = emptyMap()
)
