package dev.questweaver.core.domain.action

import dev.questweaver.core.domain.events.Event

/**
 * Represents the result of processing a player action.
 * 
 * This sealed interface captures the three possible outcomes when
 * validating and executing a player's intended action:
 * - Success: Action is valid and events were generated
 * - Failure: Action is invalid or cannot be executed
 * - RequiresChoice: Action is ambiguous and requires player clarification
 */
sealed interface ActionResult {
    /**
     * Action was successfully validated and executed.
     * 
     * @property events The game events generated by this action
     */
    data class Success(val events: List<Event>) : ActionResult
    
    /**
     * Action failed validation or execution.
     * 
     * @property reason Human-readable explanation of why the action failed
     */
    data class Failure(val reason: String) : ActionResult
    
    /**
     * Action is ambiguous and requires player to choose from options.
     * 
     * @property options The available choices the player can select from
     */
    data class RequiresChoice(val options: List<ActionOption>) : ActionResult
}
